before_install:
  - gem update bundler

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - ruby-head

script:
  - rake spec

matrix:
  allow_failures:
    - rvm: ruby-head

branches:
  only:
    - master
